In [3]:
import pandas as pd

csv_path = "news_dataset.csv"
df = pd.read_csv(csv_path, sep=',')

print("Tamaño del dataset:", df.shape)
print("Columnas:", list(df.columns))
print("Valores nulos por columna:")
print(df.isnull().sum())

display(df.head())
print()
print("Información del dataset:")
df.info()
print()
print("Estadísticas descriptivas:")
display(df.describe(include='all'))

Tamaño del dataset: (120000, 3)
Columnas: ['Class Index', 'Title', 'Description']
Valores nulos por columna:
Class Index    0
Title          0
Description    0
dtype: int64

,Class Index,Title,Description
0,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli..."
1,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...
2,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...
3,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...
4,3,"Oil prices soar to all-time record, posing new...","AFP - Tearaway world oil prices, toppling reco..."

Información del dataset:
<class 'pandas.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Class Index  120000 non-null  int64
 1   Title        120000 non-null  str
 2   Description  120000 non-null  str
dtypes: int64(1), str(2)
memory usage: 2.7 MB

Estadísticas descriptivas:

,Class Index,Title,Description
count,120000.000000,120000,120000
unique,NaN,114350,118723
top,NaN,Today's schedule,"With the economy slowly turning up, upgrading ..."
freq,NaN,39,15
mean,2.500000,NaN,NaN
std,1.118039,NaN,NaN
min,1.000000,NaN,NaN
25%,1.750000,NaN,NaN
50%,2.500000,NaN,NaN
75%,3.250000,NaN,NaN
max,4.000000,NaN,NaN